function [urbanArea,ublVars,urbanConf,forc,parameter] = UrbFluxAutosize(urbanArea,ublVars,...
        urbanConf,forc,parameter,simParam)

    urbanArea.canTemp = forc.temp;
    urbanArea.canHum = forc.hum;
    [ublVars.ublEmis,ublVars.atmTemp,urbanArea.canEmis] = InfraCalcsAir(ublVars.ublTemp,...
    ublVars.atmTemp,urbanArea.bldHeight,urbanArea.canWidth,urbanArea.canHum,urbanArea.canTemp,forc.pres,forc,parameter);
    urbanArea.canSkyLWCoef  = 4.*urbanArea.canEmis*parameter.sigma*((forc.skyTemp+urbanArea.canTemp)/2)^3.;
    
    %lw calculations
    urbanConf.canWallLWCoef  = 4.*urbanArea.canEmis*urbanConf.wall.emissivity*parameter.sigma*((urbanConf.wall.layerTemp(1)+urbanArea.canTemp)/2)^3.;
    urbanConf.canRoadLWCoef  = 4.*urbanArea.canEmis*urbanConf.road.emissivity*parameter.sigma*((urbanConf.road.layerTemp(1)+urbanArea.canTemp)/2)^3.;
    [urbanConf.road,urbanConf.wall,...
        urbanConf.roof] = InfraCalcs(urbanArea,...
    forc,urbanConf.building.glazingRatio,...
    urbanConf.road,urbanConf.wall,...
    urbanConf.roof,parameter,...
    urbanConf.canWallLWCoef,urbanConf.canRoadLWCoef);

    % builidng energy model
    urbanConf.building = BuildingEnergyModel(urbanConf.building,...
        urbanArea,urbanConf.roof,urbanConf.wall,...
        urbanConf.building,urbanConf.mass,forc.pres,parameter,simParam );

    % mass
    urbanConf.mass.layerTemp = TransientConduction(urbanConf.mass.layerTemp,...
        simParam.dt,urbanConf.mass.layerVolHeat,urbanConf.mass.layerThermalCond,...
        urbanConf.mass.layerThickness,urbanConf.building.fluxMass,1,forc.deepTemp,0.);

    % roof
    urbanConf.roof = SurfFlux( urbanConf.roof,...
        forc,parameter,simParam,forc.hum,ublVars.ublTemp,...
        forc.wind,1,urbanConf.building.fluxRoof);

    % wall
    urbanConf.wall = SurfFlux( urbanConf.wall,...
        forc,parameter,simParam,urbanArea.canHum,urbanArea.canTemp,...
        forc.wind,1,urbanConf.building.fluxWall);

    % road
    urbanConf.road = SurfFlux( urbanConf.road,...
        forc,parameter,simParam,urbanArea.canHum,urbanArea.canTemp,...
        urbanArea.canWind,2,0.);
end
