function urbanArea = UrbThermal(urbanArea,ublTemp,urbanUsage,forc,parameter,simParam)

buildingTerm = zeros(4,1);
wallTerm = zeros(2,1);
roadTerm = zeros(3,1);
dens = Density(urbanArea.canTemp,urbanArea.canHum,forc.pres);
for j = 1:numel(urbanUsage.urbanConf)
    building = urbanUsage.urbanConf(j).building;
    wall = urbanUsage.urbanConf(j).wall;
    road = urbanUsage.urbanConf(j).road;    
    buildingTerm(1)  = buildingTerm(1) +...
        urbanUsage.frac(j)*building.indoorTemp*building.glazingRatio*urbanArea.facArea*building.uValue+...
        urbanUsage.frac(j)*building.indoorTemp*building.vent*urbanArea.bldHeight/3600*urbanArea.roofArea*dens*parameter.cp+...
        urbanUsage.frac(j)*building.sensWaste*building.fWaste*(urbanArea.canWidth+urbanArea.bldWidth);
    wallTerm(1)  = wallTerm(1) +...
        urbanUsage.frac(j)*wall.layerTemp(1)*(1-building.glazingRatio)*...
        (wall.aeroCond*parameter.cp*dens+urbanUsage.urbanConf(j).canWallLWCoef)*urbanArea.facArea;
    roadTerm(1) = roadTerm(1) +...
        urbanUsage.frac(j)*road.layerTemp(1)*(road.aeroCond*parameter.cp*dens+urbanUsage.urbanConf(j).canRoadLWCoef)*urbanArea.roadArea;
    buildingTerm(2)  = buildingTerm(2) +...
        urbanUsage.frac(j)*building.glazingRatio*urbanArea.facArea*building.uValue+...
        urbanUsage.frac(j)*building.vent*urbanArea.bldHeight/3600*urbanArea.roofArea*dens*parameter.cp;
    wallTerm(2)  = wallTerm(2) +...
        urbanUsage.frac(j)*(1-building.glazingRatio)*...
        (wall.aeroCond*parameter.cp*dens+urbanUsage.urbanConf(j).canWallLWCoef)*urbanArea.facArea;
    roadTerm(2) = roadTerm(2) +...
        urbanUsage.frac(j)*(road.aeroCond*parameter.cp*dens+urbanUsage.urbanConf(j).canRoadLWCoef)*urbanArea.roadArea;
    buildingTerm(3)  = buildingTerm(3) +...
        urbanUsage.frac(j)*building.indoorHum*building.vent*urbanArea.bldHeight/3600*urbanArea.roofArea*dens*parameter.lv +...
        urbanUsage.frac(j)*building.latWaste*building.fWaste*(urbanArea.canWidth+urbanArea.bldWidth);
    roadTerm(3) = roadTerm(3) +...
        urbanUsage.frac(j)*road.lat*urbanArea.roadArea;
    buildingTerm(4)  = buildingTerm(4) +...
        urbanUsage.frac(j)*building.vent*urbanArea.bldHeight/3600*urbanArea.roofArea*dens*parameter.lv;
end
% urban air temperature
Ccan  = parameter.cp*dens*(2*urbanArea.canWidth*urbanArea.bldHeight+urbanArea.bldWidth*urbanArea.bldHeight)/simParam.dt;  
urbanArea.canTemp = (urbanArea.canTemp*Ccan +...
    wallTerm(1) + buildingTerm(1) + roadTerm(1)+...
    ublTemp*urbanArea.uExch*parameter.cp*dens*urbanArea.roadArea + ...
    forc.skyTemp*urbanArea.canSkyLWCoef*urbanArea.canWidth + ...
    urbanArea.sensAnthrop*(urbanArea.canWidth+urbanArea.bldWidth)+urbanArea.treeSensHeat*urbanArea.roadArea)/(Ccan +...
    wallTerm(2) + buildingTerm(2) + roadTerm(2) +...
    urbanArea.uExch*parameter.cp*dens*urbanArea.roadArea + urbanArea.canSkyLWCoef*urbanArea.canWidth);
% urban air humidity
Ccan  = parameter.lv*dens*(2*urbanArea.canWidth*urbanArea.bldHeight+urbanArea.bldWidth*urbanArea.bldHeight)/simParam.dt;  
urbanArea.canHum = (urbanArea.canHum*Ccan +...
    buildingTerm(3) + roadTerm(3) +...
    forc.hum*urbanArea.uExch*parameter.lv*dens*urbanArea.roadArea + ...
    urbanArea.latAnthrop*(urbanArea.canWidth+urbanArea.bldWidth)+...
    urbanArea.treeLatHeat*urbanArea.roadArea)/(Ccan +...
    buildingTerm(4) + ...
    urbanArea.uExch*parameter.lv*dens*urbanArea.roadArea);

end