CL_EPW_PATH = 'C:\Users\Jason\Desktop\test4_2\Bedford';
CL_EPW = 'bedford.epw';
CL_XML_PATH = 'C:\Users\Jason\Desktop\test4_2\Bedford\xml';
CL_XML = {
    'sensibleAnthroHeat_High.xml','sensibleAnthroHeat_Low.xml'...
    'treeCoverage_High.xml','treeCoverage_Low.xml',...
    'urbanRoadAlbedo_High.xml','urbanRoadAlbedo_Low.xml',...
    'urbanRoadK_High.xml','urbanRoadK_Low.xml',...
    'urbanRoadVegFraction_High.xml','urbanRoadVegFraction_Low.xml',...
    'urbanRoadVHC_High.xml','urbanRoadVHC_Low.xml',...
    'vHRatios_High.xml','vHRatios_Low.xml',...
    'wallVegCoverage_High.xml','wallVegCoverage_Low.xml',...
    'avgBldgHeight2_High.xml', 'avgBldgHeight2_Low.xml',...
    'concreteWall_High.xml',...
    'coolRoof_High.xml',...
    'coolRoofCA_High.xml',...
    'greenRoof_High.xml',...
    'roofVegCoverage2_High.xml',...
    'treeCoverage2_High.xml',...
    'wallVegCoverage2_High.xml',...
    };

for i = 1:length(CL_XML)
    currcity = 'Bedford-';
    run = strcat(currcity, CL_XML{i});
    disp(run); 
    [new_climate_file] = xml_inputs3(CL_EPW_PATH,CL_EPW,CL_XML_PATH,run);
end

