CL_EPW_PATH = 'C:\Users\Jason\Desktop\test4_2\Punggol';
CL_EPW = 'singapore.epw';
CL_XML_PATH = 'C:\Users\Jason\Desktop\test4_2\Punggol';
CL_XML = {
    'sensibleAnthroHeat_High.xml','sensibleAnthroHeat_Low.xml'...
    'treeCoverage_High.xml','treeCoverage_Low.xml',...
    'urbanRoadAlbedo_High.xml','urbanRoadAlbedo_Low.xml',...
    'urbanRoadK_High.xml','urbanRoadK_Low.xml',...
    'urbanRoadVegFraction_High.xml','urbanRoadVegFraction_Low.xml',...
    'urbanRoadVHC_High.xml','urbanRoadVHC_Low.xml',...
    'vHRatios_High.xml','vHRatios_Low.xml',...
    'wallVegCoverage_High.xml','wallVegCoverage_Low.xml',...
    'avgBldgHeight2_High', 'avgBldgHeight2_Low',...
    'concreteWall_High',...
    'coolRoof_High',...
    'coolRoofCA_High',...
    'greenRoof_High',...
    'roofVegCoverage2_High',...
    'treeCoverage2_High',...
    'wallVegCoverage2_High',...
    };

for i = 1:length(CL_XML)
    currcity = 'Punggol_Residential-';
    run = strcat(currcity, CL_XML{i});
    disp(run); 
    [new_climate_file] = generateEPW_10_xml_AN10_importdata(CL_EPW_PATH,CL_EPW,CL_XML_PATH,run);
end

